#ifndef ARDUINO_SENSORMOTORLAB_CONSTANTS_H
#define ARDUINO_SENSORMOTORLAB_CONSTANTS_H

enum Units { NEWTON, METER, CELSIUS };

enum PeripheralType { DC_MOTOR, RC_SERVO_MOTOR, STEPPER_MOTOR, FORCE_SENSOR, RANGE_SENSOR, THERMISTOR };

#endif /* ARDUINO_SENSORMOTORLAB_CONSTANTS_H */
