#ifndef ARDUINO_SENSORMOTORLAB_CONSTANTS_H
#define ARDUINO_SENSORMOTORLAB_CONSTANTS_H

enum Units { NEWTON, CENTIMETER, CELSIUS };
  
enum MotorType { DC_MOTOR, RC_SERVO_MOTOR, STEPPER_MOTOR, DUMMY_MOTOR };

enum SensorType { FORCE_SENSOR, POTENTIOMETER, SONAR_SENSOR, THERMISTOR, DUMMY_SENSOR };

enum MessageType { READING_GET, ANGLE_GET, ANGLE_SET, SPEED_GET, SPEED_SET, ERROR_GET, STRING_GET, SENSOR_MOTOR_BINDING_SET, ALL_STOP };
  
enum MotorFunction { SPEED, ANGLE };
  
enum Direction { CCW, CW }; 

#endif /* ARDUINO_SENSORMOTORLAB_CONSTANTS_H */
