#ifndef ARDUINO_SENSORMOTORLAB_CONSTANTS_H
#define ARDUINO_SENSORMOTORLAB_CONSTANTS_H

enum Units { NEWTON, CENTIMETER, CELSIUS };

enum PeripheralType { DC_MOTOR, RC_SERVO_MOTOR, STEPPER_MOTOR, DUMMY_MOTOR, FORCE_SENSOR, POTENTIOMETER, SONAR_SENSOR, THERMISTOR, DUMMY_SENSOR };

enum MessageType { READING };

#endif /* ARDUINO_SENSORMOTORLAB_CONSTANTS_H */
